language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy3"
sudo: false

before_script:
  - make install_dependencies

script:
  - ./bin/deployer.py --configuration=./tests/.deployer.yml --help
  - make test

